version: "3.3"

services:
  web:
    build: .
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DOCKER_TEST=TRUE
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
